# Nginx Using "Official" Nginx from Docker

FROM nginx

# Define working directory.
COPY nginx/nginx.conf /etc/nginx/nginx.conf

WORKDIR /etc/nginx

# Define default command.
CMD ["nginx"]

# Expose ports.
EXPOSE 80
